#!/usr/bin/fish
#nhentai.net manga downloader
#forked from https://github.com/SwitchAxe/nhentai-dl/

if test ( echo $argv[1] | sed 's/[0-9]*//') = ""; and test (count $argv) = "1"
    set check_if_page_exists (curl -sfL "https://www.nhentai.net/g/$argv[1]")
    if test $status != 0
        printf "%s\n" \
               "manga doesn't exist, aborting."
        exit
    end
    if not test -d "$argv[1]"
        mkdir "$argv[1]"
    end
    cd "$argv[1]"
    if test -f 1.jpg; or test -f 1.png #if there are images from previous downloads...
        rm * #...delete them.
    end
    #getting the index.html to parse:
    wget "https://www.nhentai.net/g/$argv[1]/" -q -O tempindex
    
    set gallery_number (cat tempindex | 
                        grep "window._gallery" | 
                        sed 's/\\u0022//g' | 
                        sed 's/\\\//g' | 
                        grep -E -o 'media_id:[[:digit:]]+' | 
                        sed 's/media_id://')
    #getting the pages
    
    set current_page_number 1
    while test -z (wget "https://i.nhentai.net/galleries/$gallery_number/$current_page_number.jpg" -nv 2>&1 | grep "404: Not Found");
          or test -z (wget "https://i.nhentai.net/galleries/$gallery_number/$current_page_number.png" -nv 2>&1 | grep "404: Not Found")
        printf "%s\n" "downloading page number $current_page_number"
        set current_page_number (expr $current_page_number + 1)
    end

    printf "%s" "removing leftovers... "
    if test -f "*.png"    
        rm *.png #removes leftovers
    end
    rm tempindex
    printf "%s\n" "done."
    end
